### PR TITLE
exposed SVG circle's stroke linecap

### PR DESCRIPTION
**Pull request by danielpmichalski**

### CODE REVIEW

**Review by prasannamestha — APPROVED** [review]
Thanks for the PR. You're the best!

**Comment by danielpmichalski** [comment]
@prasannamestha could you ping me when the new version is available in npm registry? :)

**Comment by prasannamestha** [comment]
sure. publishing it right away.

**Comment by prasannamestha** [comment]
It's published in npm. Cheers!

**Pull request merged**
